### ISSUE TITLE
HTML: odd behavior of side table of contents

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ogc#378] opened 2022-04-26 03:16 UTC
Table of contents in HTML output gets broken when clicking to retract it.

Check the page: https://docs.ogc.org/is/20-010/20-010.html

**Comment by ronaldtse** [comment] 2022-05-10 02:40
@s4birli would you be able to help here?

**Comment by opoudjis** [comment] 2022-05-28 14:59
Once @s4birli has actioned this, let me know so I can incorporate into metanorma. Right now, I cannot do anything about this.

**Comment by opoudjis** [comment] 2023-12-04 13:32
This still needs to be fixed. @ronaldtse we need access to a front end developer.

**Comment by ghobona** [comment] 2024-02-15 13:36
Discussed 2024-02-15

Can be closed

**Comment by opoudjis** [comment] 2024-02-15 13:36
Dupe of https://github.com/metanorma/metanorma-ogc/issues/557

**Closed by opoudjis** 2024-02-15 13:36 UTC
Labels: bug, duplicate
