### ISSUE TITLE
"No label has been processed for ID..." in certain Glossary terms

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ogc#419] opened 2022-09-14 18:11 UTC
In relation to this PR: https://github.com/metanorma/ogc-GeoPose/pull/2

"No label has been processed for ID..." message is shown for some glossary terms.
I'm not sure what could cause this issue given that the rendering of the term is
correct and its reference call (`{{<term>}}`) works as it should.

From compilation:
````
No label has been processed for ID term-accelerometer
No label has been processed for ID term-associated-reference-frame
No label has been processed for ID term-attribute
No label has been processed for ID term-barometric-pressure
No label has been processed for ID term-Bluetooth-indoor-positioning-service
No label has been processed for ID term-compass
No label has been processed for ID term-datum
No label has been processed for ID term-ellipsoid
No label has been processed for ID term-east-north-up-local-tangent-plane-coordinate-system
No label has been processed for ID term-geographic-coordinates
No label has been processed for ID term-geoid
No label has been processed for ID term-gyro
No label has been processed for ID term-local-tangent-plane-east-north-up-coordinate-system
No label has been processed for ID term-property
No label has been processed for ID term-quaternions
No label has been processed for ID term-rotation
No label has been processed for ID term-topographic-surface
No label has been processed for ID term-vertical-datum
````

**Comment by opoudjis** [comment] 2022-09-21 00:34
Duplicate of https://github.com/metanorma/ogc-GeoPose/issues/6

**Closed by opoudjis** 2022-09-21 00:34 UTC
Labels: bug

**Comment by ronaldtse** [comment] 2022-09-21 02:51
Refer to [metanorma/ogc-GeoPose#6](https://github.com/metanorma/ogc-GeoPose/issues/6) for the relevant commits.
