### ISSUE TITLE
Table of Contents does not return to previous state

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#326] opened 2021-12-03 20:16 UTC
When you contract and then expand the Table of Contents (ToC), it does not return to its previous state.

Tested with this document https://docs.ogc.org/is/19-086r4/19-086r4.html

![metanorma_ogc_toc](https://user-images.githubusercontent.com/18121038/144667219-3bbb2884-e079-472e-b6fb-50c8d5d01683.gif)

**Comment by ronaldtse** [comment] 2021-12-05 09:40
Thanks @ghobona , this is confirmed. Interestingly this issue doesn't happen with the other flavors, maybe some identifier issue.

**Comment by ronaldtse** [comment] 2021-12-06 03:47
@s4birli would you be able to help fix this in the document here (https://docs.ogc.org/is/19-086r4/19-086r4.html)?

1. Provide a JS fix for this issue 
2. Describe the fix in this ticket (maybe with a diff) so @opoudjis can implement the fix in metanorma-ogc.

Thanks!

**Comment by s4birli** [comment] 2021-12-06 06:41
This issue is due to adding the margin-left: 298px when showing the nav again.
```
$('#toggle').on('click', function(){
    if( $('nav').is(':visible') ) {
        $('nav').animate({ 'left': '-353px' }, 'slow', function(){
            $('nav').hide();
        });
        $('body').animate({ 'margin-left': '0' }, 'slow');
    }
    else {
        $('nav').show(); //newly added
        $('nav').animate({ 'left': '0px' }, 'slow');
        // $('body').animate({ 'margin-left': '298px' }, 'slow');        please delete this code
    }
});
```

**Comment by ronaldtse** [comment] 2021-12-06 09:09
Thanks @s4birli !

**Closed** 2021-12-06 12:24 UTC
Labels: bug
