### ISSUE TITLE
source block conversion leads to invalid quotation marks

### ISSUE THREAD

**Issue by jechterhoff** [metanorma/metanorma-ogc#476] opened 2022-12-09 07:02 UTC
In my document, the asciidoc source contains the following source block with JSON code:

```text
[[example_req_entitytype_jsonschema]]
.JSON Schema example with property "entityType" used for identifying the type of a JSON object
[source,json,linenumbers]
----
{
  "$schema": "http://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "Type": {
      "properties": {
        "entityType": {
          "type": "string"
        },
        "property": {
          "type": "string"
        }
      },
      "required": [
        "entityType", "property"
      ]
    }
  },
  "$ref": "#/$defs/Type"
}
----
```

The metanorma compilation result produces the following:

```text
{
  “$schema”: “http://json-schema.org/draft/2019-09/schema”,
  “$defs”: {
    “Type”: {
      “properties”: {
        “entityType”: {
          “type”: “string”
        },
        “property”: {
          “type”: “string”
        }
      },
      “required”: [
        “entityType”, “property”
      ]
    }
  },
  “$ref”: “#/$defs/Type”
}
```

Notice the change of the quotation marks in the compilation result! They are invalid in JSON. That prevents easy copy-pasting of such code examples from the specification.

The (slightly modified) [example from the UGAS-2020 engineering report](https://docs.ogc.org/per/20-012.html#jsonschema_schemaconversionrules_types_classname_typeidentification), compiled using asciidoctor and pygments as source highlighter, does not have this issue (and the line numbering is present, something that I reported for metanorma in issue #460), which supports easy copy-pasting of correct source code.

**Comment by opoudjis** [comment] 2022-12-13 14:18
Presumably duplicate of https://github.com/metanorma/metanorma-ieee/issues/191 —although I was not able to replicate the latter. Metanorma makes straight quotes smart, but is expressly meant to skip sourcecode when doing so. I need to replicate this happening to fix it.

**Comment by opoudjis** [comment] 2022-12-14 10:58
I've found the issue. Subtle one too. I was using XPath to detect instances of ancestors like "sourcecode", but neglected that such XPaths can have array indexes.

**Closed** 2022-12-14 11:03 UTC
Labels: bug

**Comment by jechterhoff** [comment] 2023-01-09 06:06
Just tested it with the latest version: works as expected now. Thanks!
