### ISSUE TITLE
(Urgent) PDF: ligature text is not copy/pastable

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#284] opened 2021-09-30 02:21 UTC
Reported by @TatjanaKutzner:

> I downloaded the PDF version of the CityGML 3.0 standard and think there is an encoding problem in the PDF.
> I cannot search for words that contain "ti".
> I wanted to search for "RelativeToTerrain", but cannot find it using the search function in my Adobe Acrobat.
>
> When I copy the word from the PDF, then it looks like this:

![ljjhnihnnnnmhnmf](https://user-images.githubusercontent.com/11865/135374909-83223c64-9d08-4adb-96da-560b03963212.png)

> Also other words like "spatial" or "definition" cannot be found.
>
> Can this problem be solved somehow?

I can confirm this problem that all the ligatures are not copy/pastable:
<img width="222" alt="image" src="https://user-images.githubusercontent.com/11865/135375003-fff7f858-81b0-431b-aea2-a8fc562bbd97.png">

<img width="137" alt="Screenshot 2021-09-30 at 10 20 14 AM" src="https://user-images.githubusercontent.com/11865/135375062-fb0e59ea-c077-4484-88fd-eb2eb6b8c139.png">

This seems to be an issue with the PDF content tree.

@Intelligent2013 can you help fix this? Thanks.

**Comment by Intelligent2013** [comment] 2021-09-30 10:30
Apache FOP replaces `ti` sequence (and some another also) to one ligature `ti` 
![image](https://user-images.githubusercontent.com/5559926/135428136-3e376e4b-5ace-41cb-860f-4787d92ded7f.png)

but Lato font doesn't contain `ti` as one glyph:
![image](https://user-images.githubusercontent.com/5559926/135437175-1983b6db-e973-4cc5-9470-62b1ff9757c2.png)

The differences between `t+i` and `ti` rendering:
![image](https://user-images.githubusercontent.com/5559926/135438864-29edbc1d-b2bc-4cc3-ae11-fbe4175e2eba.png)


Another characters replacement - `tt`:
![image](https://user-images.githubusercontent.com/5559926/135439146-589d658f-963e-4518-8fbd-1337ebe0654a.png)


Example for U+FB01 (Latin Small Ligature Fi):
![image](https://user-images.githubusercontent.com/5559926/135428983-cfeae23a-99a1-4b52-82fb-47a11d253a1c.png)

I have to investigate it.

**Comment by Intelligent2013** [comment] 2021-09-30 10:32
`ff`:
![image](https://user-images.githubusercontent.com/5559926/135439390-a201fd36-cc28-4370-b150-0917532dde23.png)

**Comment by Intelligent2013** [comment] 2021-09-30 11:16
Test for another fonts. `fi` renders as ligature in 'Source Serif Pro' and 'Lato' fonts, `ti` and `tt` render as ligature in 'Lato' only,
![image](https://user-images.githubusercontent.com/5559926/135444504-8d58fd70-a51a-4d08-b35f-42fb566eac56.png)

Found `fi` in all fonts:
![image](https://user-images.githubusercontent.com/5559926/135444665-4abd9e64-a707-4339-ae6f-3ed9d823480f.png)

Found `ti` in all fonts except 'Lato':
![image](https://user-images.githubusercontent.com/5559926/135444721-02d67806-3881-4742-8ff7-70abb72f76e7.png)

Found `tt` in all fonts except 'Lato':
![image](https://user-images.githubusercontent.com/5559926/135444851-79581c8c-9db9-4d5c-a59e-925f53c26cfd.png)

Copy-pasted to Word. `fi` replaced to sequence `f+i` for all fonts (I assumed that ligature `fi` split into two chars for Lato font, because Lato font contains such ligature), 
![image](https://user-images.githubusercontent.com/5559926/135444576-ade2afbe-0d47-478c-a007-d6933514ba89.png)

**Comment by ronaldtse** [comment] 2021-09-30 13:10
This is very interesting. However, on Google Fonts, it seems that Lato can also produce the correct ligature output while allowing copy and paste.

https://fonts.google.com/specimen/Lato?preview.text=fi&preview.text_type=custom

Is this a PDF issue?

**Comment by Intelligent2013** [comment] 2021-09-30 13:20
> This is very interesting. However, on Google Fonts, it seems that Lato can also produce the correct ligature output while allowing copy and paste.

Apache FOP and Lato produce correct ligature for `fi`:
![image](https://user-images.githubusercontent.com/5559926/135444665-4abd9e64-a707-4339-ae6f-3ed9d823480f.png)

But it seems FOP creates 'virtual' ligatures for some pairs and can't produce reverse feature for search and copy-paste.

I think this is Apache FOP issue. I've created Word document and saved as PDF from Word, and there aren't any ligatures:
![image](https://user-images.githubusercontent.com/5559926/135461784-35c8ffae-4fd2-4a9a-9497-725d6a826886.png)
I'm trying to find in Apache FOP where can we turn-off ligature feature...

**Comment by Intelligent2013** [comment] 2021-09-30 13:48
Actually, Lato font contains ligatures for `ti` and `tt`:
![image](https://user-images.githubusercontent.com/5559926/135466146-c4e84028-71b8-4e0e-ac7d-bd0a785ab099.png)

![image](https://user-images.githubusercontent.com/5559926/135466316-5ad92e3f-234e-4bba-9136-2b3a25591372.png)

Before I've used CharMap Windows tool, but it doesn't show glyph > U+FFFF.

**Comment by Intelligent2013** [comment] 2021-09-30 17:45
The Apache FOP class responsible for ligatures is `src\main\java\org\apache\fop\complexscripts\fonts\GlyphSubstitutionTable.java`.

If the function `findLigature` will return `null` always, then it solves this issue, i.e. no ligatures will be used in pdf:
```java
        private Ligature findLigature(LigatureSet ls, int[] glyphs) {
            Ligature[] la = ls.getLigatures();
            int k = -1;
            int maxComponents = -1;
            for (int i = 0, n = la.length; i < n; i++) {
                Ligature l = la [ i ];
                if (l.matchesComponents(glyphs)) {
                    int nc = l.getNumComponents();
                    if (nc > maxComponents) {
                        maxComponents = nc;
                        k = i;
                    }
                }
            }
            if (k >= 0) {
                return null;
                //return la [ k ];
            } else {
                return null;
            }
        }
```

but Arabic documents will be rendered non-correctly. Will try to deep into the FOP code...

**Comment by Intelligent2013** [comment] 2021-09-30 19:59
Preliminary result - `unicodeMappings` array (src\main\java\org\apache\fop\fonts\truetype\OpenFont.java) contains max unicode index `65535`:
![image](https://user-images.githubusercontent.com/5559926/135521700-96620826-7332-4d8b-9b6e-e77aa61c5334.png)

but ligatures `tt` - `65574`, `ti` - `66260`.

**Comment by Intelligent2013** [comment] 2021-10-01 16:46
- Apache FOP has very limited support of ligatures.  https://xmlgraphics.apache.org/fop/2.5/fonts.html:
`OpenType fonts support advanced layout features such as ligatures, small caps, swashes, alternates, old style figures and more. Please see Advanced Typographic Extensions - OpenType Layout. These features are currently missing within FOP due to the implementation opting to favor a greater number of formats.`

For our case, Apache FOP can't substitute characters pairs for ligatures more than 65535. Investigating about how to process glyph more that 65535 will take a lot of time for me and I think will be a lot of negative side-effects after fixing...

- Lato font has very strange ligature for 'fi' - i without dot above:
![image](https://user-images.githubusercontent.com/5559926/135657207-7d4fb47d-2ade-4d5f-a875-5626f9dac0da.png)
I think this behavior is not obvious for end-user. We can't turn-on/off ligatures processing via xsl-fo/config etc.

@ronaldtse  therefore, I propose to turn-off ligature feature in Apache FOP for all languages except Arabic.

**Comment by ronaldtse** [comment] 2021-10-03 03:39
@Intelligent2013 let's turn off ligatures for non-Arabic then.

**Comment by Intelligent2013** [comment] 2021-10-03 19:31
Issue fixed in mn2pdf v1.37 https://github.com/metanorma/mn2pdf/releases/tag/v1.37

**Comment by opoudjis** [comment] 2021-10-04 04:06
... I think turning off ligatures in Roman is ugly (and if you want ugly text, why use PDF at all?), but I understand why we have to do it. 

Is there any option of leaving in ligatures with codepoint < 0xFFFF, so it ligates tt and not ti? You could also manually insert ZWJ in select pairs in preprocessing, but I don't know if that would help or make it worse.

The lack of a dot in the "fi" ligature is possibly old fashioned, but it is not unreasonable.

**Comment by ronaldtse** [comment] 2021-10-04 04:23
> Preliminary result - unicodeMappings array (src\main\java\org\apache\fop\fonts\truetype\OpenFont.java) contains max unicode index 65535:

@Intelligent2013 does this mean if we can fix the 65535 limit (the problem is FOP cannot fix ligatures above code point 65535), then the original setup will work?

Perhaps we can try fixing that and contributing it back to Apache FOP?

**Comment by Intelligent2013** [comment] 2021-10-05 14:00
There is an issue on Apache tracker: https://issues.apache.org/jira/browse/FOP-2701

The problem is similar, but isn't exactly same:
- when set `<fo:root ... xml:lang="en">` (we should use the attribute `xml:lang` for PDF/UA requirement), then there aren't any ligatures for Calibri font:
![image](https://user-images.githubusercontent.com/5559926/136035697-a4051ceb-964d-45b3-86b3-b98a34177b82.png)

- without `xml:lang` - there are ligatures for Calibri, but `ti` and `tt` can't be found (and copy-pasted as one unicode char, not decomposed characters):
![image](https://user-images.githubusercontent.com/5559926/136035273-aaaf8ab0-af6f-4dca-b74b-6b658ff7b653.png)


For Lato font, `xml:lang` doesn't effect  - `ti` and `tt` are not searchable both:
![image](https://user-images.githubusercontent.com/5559926/136038104-70ed9b57-dc73-4ad8-8fbd-795cd31063b6.png)


For 'EB Garamond 12' font we have another problem:
![image](https://user-images.githubusercontent.com/5559926/136036830-8903654d-0bcf-4583-b268-7c22cb1d4181.png)
- 'ff', 'fi', 'fl', 'ffi' aren't searchable 
- `ti`, `tt` are searchable
- each copy-pasted character represented as one Unicode char (not one char for each ligature)
![image](https://user-images.githubusercontent.com/5559926/136037081-ed0db7ea-bd48-4ff4-b8c0-0091d819c51d.png)

**Comment by Intelligent2013** [comment] 2021-10-05 14:08
Using of `embedding-mode="full"` doesn't have effect (except bigger size of PDF).

**Comment by Intelligent2013** [comment] 2021-10-05 17:11
> > Preliminary result - unicodeMappings array (src\main\java\org\apache\fop\fonts\truetype\OpenFont.java) contains max unicode index 65535:
> 
> @Intelligent2013 does this mean if we can fix the 65535 limit (the problem is FOP cannot fix ligatures above code point 65535), then the original setup will work?
> 
> Perhaps we can try fixing that and contributing it back to Apache FOP?

yes, the problem is that Apache FOP replaces sequence of characters to one char (one ligature, even with code point more 65535), but don't put original characters (if ligature char more than 65535) for search and copy-paste feature. But actually this is partial issue as you can see above, for Cambria font Apache FOP doesn't put ligatures at all. I.e. there are interrelated things:
- the attribute `xml:lang`
- font file
- characters replacement issue in Apache FOP

I'll try to investigate these issue, but I don't figure out how long it will take...

**Comment by ronaldtse** [comment] 2021-10-06 05:09
Moving this to a new issue in mn2pdf.

**Closed** 2021-10-06 05:12 UTC
Labels: bug
