### ISSUE TITLE
Colon missing from NOTE when rendered as HTML

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#472] opened 2022-12-06 17:12 UTC
The generated HTML documents do not include colons when rendering notes. See attached screenshot.

This confuses readers. The word "NOTE" should immediately be followed by a colon ":" .

![Screenshot 2022-12-06 at 17 09 16](https://user-images.githubusercontent.com/18121038/205977336-87d6fc4e-5f4c-4b31-8b87-c12ecc555d12.png)

**Comment by opoudjis** [comment] 2022-12-19 01:41
@Intelligent2013 I'm going to do this right after release, adding `:` to all /note/name in Presentation XML. I'll need you to confirm that you are taking `:` off, if you're adding it.

I'm assuming in all of this that we universally put space or tab between /{block}/name and /{block}/{text}, and that punctuation like `:` needs to get inserted at the end of /{block}/name .

**Comment by ronaldtse** [comment] 2022-12-19 04:35
@opoudjis this seems to be a purely HTML output presentation issue. I don’t understand why the Presentation XML is affected.

**Comment by Intelligent2013** [comment] 2022-12-19 08:11
Currently, XSLT puts these characters after `note/name`:
- BIPM: 'space'
- IEEE: '—' (em dash, 2014hex)
- GB, IHO, M3AAWG, OGC, UNECE, Ribose: ':'
- ITU, NIST: ' – ' (en dash with spaces around, 2013hex)

> I'm going to do this right after release, adding `:` to all /note/name in Presentation XML. I'll need you to confirm that you are taking `:` off, if you're adding it.

@opoudjis would you like to put `:` for OGC only, or update Presentation XML for all flavors?

**Comment by opoudjis** [comment] 2022-12-20 13:21
@ronaldtse This is why; we've allowed Pdf and Html to diverge, and they should not. 

Yes,  @Intelligent2013 , I'd like the delimiter to be in the Presentation XML.

**Comment by ronaldtse** [comment] 2022-12-21 14:07
> @ronaldtse This is why; we've allowed Pdf and Html to diverge, and they should not.

Completely disagree. PDF and HTML are different types of media.

**Comment by opoudjis** [comment] 2022-12-22 14:42
After a lot of debate, we'll realise the delimiters between labels and contents as XSLT stylesheets that will be included in the Presentation XML header, and that can be specific to an output type.

**Comment by opoudjis** [comment] 2022-12-24 09:51
This is going to be the initial test case for this mode of Presentation XML.

I'm going to also be migrating rendering-specific content from /misc-container to /render

**Comment by opoudjis** [comment] 2022-12-24 10:16
I will need to add 

````
<xsl:template match="node() | @*">
    <xsl:copy>
        <xsl:apply-templates select="node() | @*"/>
    </xsl:copy>
</xsl:template>
````

to my XSLT run, so that the Presentation XML passes through. I am leaving it out of the Presentation XML inclusion, so you pick only the rendering rules as a priority.

**Comment by opoudjis** [comment] 2022-12-24 12:57
[a.presentation 2.xml.zip](https://github.com/metanorma/metanorma-ogc/files/10298605/a.presentation.2.xml.zip)

@Intelligent2013 This is the trial version including XSLT preprocessing. Please confirm that you can use it.

**Comment by opoudjis** [comment] 2022-12-24 13:06
@ronaldtse 

Extending this "refactoring" to the whole of Metanorma is a big task, and one I encourage you to delegate the task to another developer.

**Comment by Intelligent2013** [comment] 2022-12-24 14:50
> [a.presentation 2.xml.zip](https://github.com/metanorma/metanorma-ogc/files/10298605/a.presentation.2.xml.zip)
> 
> @Intelligent2013 This is the trial version including XSLT preprocessing. Please confirm that you can use it.

@opoudjis Confirm, I can use it.

**Comment by Intelligent2013** [comment] 2022-12-24 14:59
> My question now is, are there any circumstances when you are populating that sfx parameter, that I need to be aware of?

@opoudjis no, the `sfx` parameter isn't using anywhere. At one time I did refactoring and this parameter is out of date.

**Comment by opoudjis** [comment] 2022-12-26 04:20
OK

I am going to close this ticket once you have confirmed this as done, @Intelligent2013. I am writing a separate ticket to roll this out across all flavours and all block types, but it will have to wait, since it will take a long time to implement, and I have more urgent tasks.

**Closed** 2022-12-30 05:58 UTC
Labels: enhancement
